"""Per-URL feature table for the false-positive investigation (docs/false_positive_investigation.md).

    python scripts/feature_comparison.py

Uses the production code path (ml.predictor.Predictor -> ml.feature_extractor) for two models:
  v1.2.0  host view          (models/previous_v1.2.0, archived)
  v2.0.0  registrable view   (models/, deployed)
Dataset examples are drawn from the VALIDATION split of the registrable-grouped split (the test split is
reserved for the one-time final evaluation). Real-world and test-suite URLs are hand-picked and labelled as such.
Writes docs/data/feature_comparison.json and docs/data/feature_comparison.md.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from ml.dataset import load_registrable_grouped_split  # noqa: E402
from ml.feature_schema import FEATURE_NAMES  # noqa: E402
from ml.predictor import Predictor  # noqa: E402
from ml.url_utils import split_registrable  # noqa: E402

OUT_JSON = ROOT / "docs" / "data" / "feature_comparison.json"
OUT_MD = ROOT / "docs" / "data" / "feature_comparison.md"
SHORT = {"URLLength": "Len", "DomainLength": "DomLen", "IsDomainIP": "IP", "CharContinuationRate": "CharCont",
         "TLDLegitimateProb": "TLDProb", "TLDLength": "TLDLen", "NoOfSubDomain": "SubDom",
         "NoOfLettersInURL": "Letters", "LetterRatioInURL": "LetRatio", "NoOfDegitsInURL": "Digits",
         "DegitRatioInURL": "DigRatio", "NoOfEqualsInURL": "Eq", "NoOfQMarkInURL": "QMark",
         "NoOfAmpersandInURL": "Pct", "NoOfOtherSpecialCharsInURL": "Special", "SpacialCharRatioInURL": "SpecRatio",
         "IsHTTPS": "HTTPS"}

HAND_PICKED = [
    ("real-world legitimate: dashboard/subdomain", "legitimate", [
        "https://admob.google.com/v2/home", "https://publisher.unity.com/packages", "https://dashboard.render.com/",
        "https://dash.cloudflare.com/", "https://mail.google.com/mail/u/0/", "https://docs.python.org/3/"]),
    ("real-world legitimate: simple / path / query", "legitimate", [
        "https://claude.ai/chat", "https://www.wikipedia.org", "https://github.com/pallets/flask",
        "https://www.google.com/search?q=phishing"]),
    ("test-suite phishing-style URLs (tests/)", "phishing (test URL)", [
        "http://paypal-login-secure-verify.account-update.xyz/signin", "http://login.paypal.com.evil.xyz/signin",
        "http://45.77.10.3/secure/login.php", "https://jhjhgfg-3176c.firebaseapp.com/"]),
]


def dataset_examples(validation):
    host = validation["normalized_url"].str.extract(r"^https?://(?:[^@/]*@)?([^/:?#]+)")[0].str.lower()
    sub = host.map(lambda h: split_registrable(h)[0])
    legit, phish = validation["label"] == 1, validation["label"] == 0
    plain = sub.isin(["", "www"])
    shared = host.map(lambda h: split_registrable(h)[1] == h and h.count(".") >= 2 and "." in h)
    picks = [
        ("dataset legitimate: homepage", "legitimate", validation[legit & plain]),
        ("dataset legitimate: host with subdomain", "legitimate", validation[legit & ~plain]),
        ("dataset phishing: subdomain of attacker domain", "phishing", validation[phish & ~plain]),
        ("dataset phishing: shared-hosting site", "phishing", validation[phish & shared]),
        ("dataset phishing: plain registered domain", "phishing", validation[phish & plain & ~shared]),
    ]
    return [(group, label, df.sample(min(3, len(df)), random_state=11)["URL"].tolist()) for group, label, df in picks]


def main():
    v12 = Predictor.from_paths(*(ROOT / "models" / "previous_v1.2.0" / f for f in
                                 ("phishing_model.pkl", "model_metadata.json", "tld_legitimate_prob.json")))
    v20 = Predictor.from_paths()
    validation = load_registrable_grouped_split()[0]["validation"]
    rows = []
    for group, label, urls in dataset_examples(validation) + HAND_PICKED:
        for url in urls:
            a, b = v12.predict(url), v20.predict(url)
            rows.append({"group": group, "label": label, "url": url,
                         "v1_2_0_host_view": {"model_input": a["model_input"], "prediction": a["prediction"],
                                              "p_phishing": a["phishing_probability"], "risk": a["risk_level"],
                                              "features": a["features"]},
                         "v2_0_0_registrable_view": {"model_input": b["model_input"], "prediction": b["prediction"],
                                                     "p_phishing": b["phishing_probability"], "risk": b["risk_level"],
                                                     "features": b["features"]}})
    OUT_JSON.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")

    md = ["<!-- Generated by `python scripts/feature_comparison.py`. Do not edit by hand. -->", "",
          "## Predictions: v1.2.0 (host view) vs v2.0.0 (registrable view)", "",
          "| Group | Label | URL | v1.2.0 input | v1.2.0 | v2.0.0 input | v2.0.0 |", "|---|---|---|---|---|---|---|"]
    for r in rows:
        a, b = r["v1_2_0_host_view"], r["v2_0_0_registrable_view"]
        md.append(f"| {r['group']} | {r['label']} | `{r['url'][:70]}` | `{a['model_input']}` | {a['prediction']} "
                  f"({a['p_phishing']:.3f}) | `{b['model_input']}` | {b['prediction']} ({b['p_phishing']:.3f}) |")
    for key, title in (("v1_2_0_host_view", "v1.2.0 host-view features"),
                       ("v2_0_0_registrable_view", "v2.0.0 registrable-view features")):
        md += ["", f"## {title} (all 17, schema order)", "",
               "| URL | " + " | ".join(SHORT[f] for f in FEATURE_NAMES) + " |",
               "|---|" + "---|" * len(FEATURE_NAMES)]
        for r in rows:
            f = r[key]["features"]
            md.append(f"| `{r['url'][:50]}` | " + " | ".join(
                f"{f[n]:.3g}" if isinstance(f[n], float) else str(f[n]) for n in FEATURE_NAMES) + " |")
    md += ["", "Column key: " + ", ".join(f"{v} = {k}" for k, v in SHORT.items()) + "."]
    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")
    print("\n".join(md[:len(rows) + 5]))


if __name__ == "__main__":
    main()
